//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace IntegratedResourceManagementSystem.Reports.ReportDataSet {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("SummaryOfMonthlyInventoryPerBrandDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class SummaryOfMonthlyInventoryPerBrandDataSet : global::System.Data.DataSet {
        
        private SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public SummaryOfMonthlyInventoryPerBrandDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected SummaryOfMonthlyInventoryPerBrandDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["SummaryOfMonthlyInventoryPerBrandDataSetDataTable"] != null)) {
                    base.Tables.Add(new SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable(ds.Tables["SummaryOfMonthlyInventoryPerBrandDataSetDataTable"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable SummaryOfMonthlyInventoryPerBrandDataSetDataTable {
            get {
                return this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            SummaryOfMonthlyInventoryPerBrandDataSet cln = ((SummaryOfMonthlyInventoryPerBrandDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["SummaryOfMonthlyInventoryPerBrandDataSetDataTable"] != null)) {
                    base.Tables.Add(new SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable(ds.Tables["SummaryOfMonthlyInventoryPerBrandDataSetDataTable"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable = ((SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable)(base.Tables["SummaryOfMonthlyInventoryPerBrandDataSetDataTable"]));
            if ((initTable == true)) {
                if ((this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable != null)) {
                    this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "SummaryOfMonthlyInventoryPerBrandDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/SummaryOfMonthlyInventoryPerBrandDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable = new SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable();
            base.Tables.Add(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeSummaryOfMonthlyInventoryPerBrandDataSetDataTable() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            SummaryOfMonthlyInventoryPerBrandDataSet ds = new SummaryOfMonthlyInventoryPerBrandDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChangeEventHandler(object sender, SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable : global::System.Data.TypedTableBase<SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow> {
            
            private global::System.Data.DataColumn columnDATE_FROM;
            
            private global::System.Data.DataColumn columnDATE_TO;
            
            private global::System.Data.DataColumn columnCUSTOMER;
            
            private global::System.Data.DataColumn columnBRAND_NAME;
            
            private global::System.Data.DataColumn columnCUSTOMER_TYPE;
            
            private global::System.Data.DataColumn columnBALANCE_QTY;
            
            private global::System.Data.DataColumn columnBALANCE_AMT;
            
            private global::System.Data.DataColumn columnBALANCE_COST;
            
            private global::System.Data.DataColumn columnDR_QTY;
            
            private global::System.Data.DataColumn columnDR_AMT;
            
            private global::System.Data.DataColumn columnDR_COST;
            
            private global::System.Data.DataColumn columnRETURN_QTY;
            
            private global::System.Data.DataColumn columnRETURN_AMT;
            
            private global::System.Data.DataColumn columnRETURN_COST;
            
            private global::System.Data.DataColumn columnSALES_QTY;
            
            private global::System.Data.DataColumn columnSALES_AMT;
            
            private global::System.Data.DataColumn columnSALES_COST;
            
            private global::System.Data.DataColumn columnADJ_QTY;
            
            private global::System.Data.DataColumn columnADJ_AMT;
            
            private global::System.Data.DataColumn columnADJ_COST;
            
            private global::System.Data.DataColumn columnUSERNAME;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable() {
                this.TableName = "SummaryOfMonthlyInventoryPerBrandDataSetDataTable";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DATE_FROMColumn {
                get {
                    return this.columnDATE_FROM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DATE_TOColumn {
                get {
                    return this.columnDATE_TO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CUSTOMERColumn {
                get {
                    return this.columnCUSTOMER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BRAND_NAMEColumn {
                get {
                    return this.columnBRAND_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CUSTOMER_TYPEColumn {
                get {
                    return this.columnCUSTOMER_TYPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BALANCE_QTYColumn {
                get {
                    return this.columnBALANCE_QTY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BALANCE_AMTColumn {
                get {
                    return this.columnBALANCE_AMT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BALANCE_COSTColumn {
                get {
                    return this.columnBALANCE_COST;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DR_QTYColumn {
                get {
                    return this.columnDR_QTY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DR_AMTColumn {
                get {
                    return this.columnDR_AMT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DR_COSTColumn {
                get {
                    return this.columnDR_COST;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn RETURN_QTYColumn {
                get {
                    return this.columnRETURN_QTY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn RETURN_AMTColumn {
                get {
                    return this.columnRETURN_AMT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn RETURN_COSTColumn {
                get {
                    return this.columnRETURN_COST;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SALES_QTYColumn {
                get {
                    return this.columnSALES_QTY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SALES_AMTColumn {
                get {
                    return this.columnSALES_AMT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SALES_COSTColumn {
                get {
                    return this.columnSALES_COST;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ADJ_QTYColumn {
                get {
                    return this.columnADJ_QTY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ADJ_AMTColumn {
                get {
                    return this.columnADJ_AMT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ADJ_COSTColumn {
                get {
                    return this.columnADJ_COST;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn USERNAMEColumn {
                get {
                    return this.columnUSERNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow this[int index] {
                get {
                    return ((SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChangeEventHandler SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChangeEventHandler SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChangeEventHandler SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChangeEventHandler SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddSummaryOfMonthlyInventoryPerBrandDataSetDataTableRow(SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow AddSummaryOfMonthlyInventoryPerBrandDataSetDataTableRow(
                        System.DateTime DATE_FROM, 
                        System.DateTime DATE_TO, 
                        string CUSTOMER, 
                        string BRAND_NAME, 
                        string CUSTOMER_TYPE, 
                        int BALANCE_QTY, 
                        double BALANCE_AMT, 
                        double BALANCE_COST, 
                        int DR_QTY, 
                        double DR_AMT, 
                        double DR_COST, 
                        int RETURN_QTY, 
                        double RETURN_AMT, 
                        double RETURN_COST, 
                        int SALES_QTY, 
                        double SALES_AMT, 
                        double SALES_COST, 
                        int ADJ_QTY, 
                        double ADJ_AMT, 
                        double ADJ_COST, 
                        string USERNAME) {
                SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow rowSummaryOfMonthlyInventoryPerBrandDataSetDataTableRow = ((SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        DATE_FROM,
                        DATE_TO,
                        CUSTOMER,
                        BRAND_NAME,
                        CUSTOMER_TYPE,
                        BALANCE_QTY,
                        BALANCE_AMT,
                        BALANCE_COST,
                        DR_QTY,
                        DR_AMT,
                        DR_COST,
                        RETURN_QTY,
                        RETURN_AMT,
                        RETURN_COST,
                        SALES_QTY,
                        SALES_AMT,
                        SALES_COST,
                        ADJ_QTY,
                        ADJ_AMT,
                        ADJ_COST,
                        USERNAME};
                rowSummaryOfMonthlyInventoryPerBrandDataSetDataTableRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowSummaryOfMonthlyInventoryPerBrandDataSetDataTableRow);
                return rowSummaryOfMonthlyInventoryPerBrandDataSetDataTableRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable cln = ((SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnDATE_FROM = base.Columns["DATE_FROM"];
                this.columnDATE_TO = base.Columns["DATE_TO"];
                this.columnCUSTOMER = base.Columns["CUSTOMER"];
                this.columnBRAND_NAME = base.Columns["BRAND_NAME"];
                this.columnCUSTOMER_TYPE = base.Columns["CUSTOMER_TYPE"];
                this.columnBALANCE_QTY = base.Columns["BALANCE_QTY"];
                this.columnBALANCE_AMT = base.Columns["BALANCE_AMT"];
                this.columnBALANCE_COST = base.Columns["BALANCE_COST"];
                this.columnDR_QTY = base.Columns["DR_QTY"];
                this.columnDR_AMT = base.Columns["DR_AMT"];
                this.columnDR_COST = base.Columns["DR_COST"];
                this.columnRETURN_QTY = base.Columns["RETURN_QTY"];
                this.columnRETURN_AMT = base.Columns["RETURN_AMT"];
                this.columnRETURN_COST = base.Columns["RETURN_COST"];
                this.columnSALES_QTY = base.Columns["SALES_QTY"];
                this.columnSALES_AMT = base.Columns["SALES_AMT"];
                this.columnSALES_COST = base.Columns["SALES_COST"];
                this.columnADJ_QTY = base.Columns["ADJ_QTY"];
                this.columnADJ_AMT = base.Columns["ADJ_AMT"];
                this.columnADJ_COST = base.Columns["ADJ_COST"];
                this.columnUSERNAME = base.Columns["USERNAME"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnDATE_FROM = new global::System.Data.DataColumn("DATE_FROM", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDATE_FROM);
                this.columnDATE_TO = new global::System.Data.DataColumn("DATE_TO", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDATE_TO);
                this.columnCUSTOMER = new global::System.Data.DataColumn("CUSTOMER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCUSTOMER);
                this.columnBRAND_NAME = new global::System.Data.DataColumn("BRAND_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBRAND_NAME);
                this.columnCUSTOMER_TYPE = new global::System.Data.DataColumn("CUSTOMER_TYPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCUSTOMER_TYPE);
                this.columnBALANCE_QTY = new global::System.Data.DataColumn("BALANCE_QTY", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBALANCE_QTY);
                this.columnBALANCE_AMT = new global::System.Data.DataColumn("BALANCE_AMT", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBALANCE_AMT);
                this.columnBALANCE_COST = new global::System.Data.DataColumn("BALANCE_COST", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBALANCE_COST);
                this.columnDR_QTY = new global::System.Data.DataColumn("DR_QTY", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDR_QTY);
                this.columnDR_AMT = new global::System.Data.DataColumn("DR_AMT", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDR_AMT);
                this.columnDR_COST = new global::System.Data.DataColumn("DR_COST", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDR_COST);
                this.columnRETURN_QTY = new global::System.Data.DataColumn("RETURN_QTY", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRETURN_QTY);
                this.columnRETURN_AMT = new global::System.Data.DataColumn("RETURN_AMT", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRETURN_AMT);
                this.columnRETURN_COST = new global::System.Data.DataColumn("RETURN_COST", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRETURN_COST);
                this.columnSALES_QTY = new global::System.Data.DataColumn("SALES_QTY", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSALES_QTY);
                this.columnSALES_AMT = new global::System.Data.DataColumn("SALES_AMT", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSALES_AMT);
                this.columnSALES_COST = new global::System.Data.DataColumn("SALES_COST", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSALES_COST);
                this.columnADJ_QTY = new global::System.Data.DataColumn("ADJ_QTY", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnADJ_QTY);
                this.columnADJ_AMT = new global::System.Data.DataColumn("ADJ_AMT", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnADJ_AMT);
                this.columnADJ_COST = new global::System.Data.DataColumn("ADJ_COST", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnADJ_COST);
                this.columnUSERNAME = new global::System.Data.DataColumn("USERNAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSERNAME);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow NewSummaryOfMonthlyInventoryPerBrandDataSetDataTableRow() {
                return ((SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChanged != null)) {
                    this.SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChanged(this, new SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChangeEvent(((SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChanging != null)) {
                    this.SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChanging(this, new SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChangeEvent(((SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowDeleted != null)) {
                    this.SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowDeleted(this, new SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChangeEvent(((SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowDeleting != null)) {
                    this.SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowDeleting(this, new SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChangeEvent(((SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveSummaryOfMonthlyInventoryPerBrandDataSetDataTableRow(SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                SummaryOfMonthlyInventoryPerBrandDataSet ds = new SummaryOfMonthlyInventoryPerBrandDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow : global::System.Data.DataRow {
            
            private SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable = ((SummaryOfMonthlyInventoryPerBrandDataSetDataTableDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime DATE_FROM {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DATE_FROMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DATE_FROM\' in table \'SummaryOfMonthlyInventoryPerBrandDataS" +
                                "etDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DATE_FROMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime DATE_TO {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DATE_TOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DATE_TO\' in table \'SummaryOfMonthlyInventoryPerBrandDataSet" +
                                "DataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DATE_TOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string CUSTOMER {
                get {
                    try {
                        return ((string)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.CUSTOMERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CUSTOMER\' in table \'SummaryOfMonthlyInventoryPerBrandDataSe" +
                                "tDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.CUSTOMERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string BRAND_NAME {
                get {
                    try {
                        return ((string)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BRAND_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BRAND_NAME\' in table \'SummaryOfMonthlyInventoryPerBrandData" +
                                "SetDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BRAND_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string CUSTOMER_TYPE {
                get {
                    try {
                        return ((string)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.CUSTOMER_TYPEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CUSTOMER_TYPE\' in table \'SummaryOfMonthlyInventoryPerBrandD" +
                                "ataSetDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.CUSTOMER_TYPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int BALANCE_QTY {
                get {
                    try {
                        return ((int)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BALANCE_QTYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BALANCE_QTY\' in table \'SummaryOfMonthlyInventoryPerBrandDat" +
                                "aSetDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BALANCE_QTYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double BALANCE_AMT {
                get {
                    try {
                        return ((double)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BALANCE_AMTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BALANCE_AMT\' in table \'SummaryOfMonthlyInventoryPerBrandDat" +
                                "aSetDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BALANCE_AMTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double BALANCE_COST {
                get {
                    try {
                        return ((double)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BALANCE_COSTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BALANCE_COST\' in table \'SummaryOfMonthlyInventoryPerBrandDa" +
                                "taSetDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BALANCE_COSTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int DR_QTY {
                get {
                    try {
                        return ((int)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DR_QTYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DR_QTY\' in table \'SummaryOfMonthlyInventoryPerBrandDataSetD" +
                                "ataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DR_QTYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double DR_AMT {
                get {
                    try {
                        return ((double)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DR_AMTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DR_AMT\' in table \'SummaryOfMonthlyInventoryPerBrandDataSetD" +
                                "ataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DR_AMTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double DR_COST {
                get {
                    try {
                        return ((double)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DR_COSTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DR_COST\' in table \'SummaryOfMonthlyInventoryPerBrandDataSet" +
                                "DataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DR_COSTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int RETURN_QTY {
                get {
                    try {
                        return ((int)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.RETURN_QTYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RETURN_QTY\' in table \'SummaryOfMonthlyInventoryPerBrandData" +
                                "SetDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.RETURN_QTYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double RETURN_AMT {
                get {
                    try {
                        return ((double)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.RETURN_AMTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RETURN_AMT\' in table \'SummaryOfMonthlyInventoryPerBrandData" +
                                "SetDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.RETURN_AMTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double RETURN_COST {
                get {
                    try {
                        return ((double)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.RETURN_COSTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RETURN_COST\' in table \'SummaryOfMonthlyInventoryPerBrandDat" +
                                "aSetDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.RETURN_COSTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int SALES_QTY {
                get {
                    try {
                        return ((int)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.SALES_QTYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SALES_QTY\' in table \'SummaryOfMonthlyInventoryPerBrandDataS" +
                                "etDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.SALES_QTYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double SALES_AMT {
                get {
                    try {
                        return ((double)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.SALES_AMTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SALES_AMT\' in table \'SummaryOfMonthlyInventoryPerBrandDataS" +
                                "etDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.SALES_AMTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double SALES_COST {
                get {
                    try {
                        return ((double)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.SALES_COSTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SALES_COST\' in table \'SummaryOfMonthlyInventoryPerBrandData" +
                                "SetDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.SALES_COSTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int ADJ_QTY {
                get {
                    try {
                        return ((int)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.ADJ_QTYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ADJ_QTY\' in table \'SummaryOfMonthlyInventoryPerBrandDataSet" +
                                "DataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.ADJ_QTYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double ADJ_AMT {
                get {
                    try {
                        return ((double)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.ADJ_AMTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ADJ_AMT\' in table \'SummaryOfMonthlyInventoryPerBrandDataSet" +
                                "DataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.ADJ_AMTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double ADJ_COST {
                get {
                    try {
                        return ((double)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.ADJ_COSTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ADJ_COST\' in table \'SummaryOfMonthlyInventoryPerBrandDataSe" +
                                "tDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.ADJ_COSTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string USERNAME {
                get {
                    try {
                        return ((string)(this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.USERNAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'USERNAME\' in table \'SummaryOfMonthlyInventoryPerBrandDataSe" +
                                "tDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.USERNAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDATE_FROMNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DATE_FROMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDATE_FROMNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DATE_FROMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDATE_TONull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DATE_TOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDATE_TONull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DATE_TOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCUSTOMERNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.CUSTOMERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCUSTOMERNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.CUSTOMERColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBRAND_NAMENull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BRAND_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBRAND_NAMENull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BRAND_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCUSTOMER_TYPENull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.CUSTOMER_TYPEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCUSTOMER_TYPENull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.CUSTOMER_TYPEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBALANCE_QTYNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BALANCE_QTYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBALANCE_QTYNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BALANCE_QTYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBALANCE_AMTNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BALANCE_AMTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBALANCE_AMTNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BALANCE_AMTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBALANCE_COSTNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BALANCE_COSTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBALANCE_COSTNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.BALANCE_COSTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDR_QTYNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DR_QTYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDR_QTYNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DR_QTYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDR_AMTNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DR_AMTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDR_AMTNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DR_AMTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDR_COSTNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DR_COSTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDR_COSTNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.DR_COSTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsRETURN_QTYNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.RETURN_QTYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetRETURN_QTYNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.RETURN_QTYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsRETURN_AMTNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.RETURN_AMTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetRETURN_AMTNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.RETURN_AMTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsRETURN_COSTNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.RETURN_COSTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetRETURN_COSTNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.RETURN_COSTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSALES_QTYNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.SALES_QTYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSALES_QTYNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.SALES_QTYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSALES_AMTNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.SALES_AMTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSALES_AMTNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.SALES_AMTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSALES_COSTNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.SALES_COSTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSALES_COSTNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.SALES_COSTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsADJ_QTYNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.ADJ_QTYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetADJ_QTYNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.ADJ_QTYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsADJ_AMTNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.ADJ_AMTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetADJ_AMTNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.ADJ_AMTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsADJ_COSTNull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.ADJ_COSTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetADJ_COSTNull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.ADJ_COSTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsUSERNAMENull() {
                return this.IsNull(this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.USERNAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetUSERNAMENull() {
                this[this.tableSummaryOfMonthlyInventoryPerBrandDataSetDataTable.USERNAMEColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChangeEvent : global::System.EventArgs {
            
            private SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public SummaryOfMonthlyInventoryPerBrandDataSetDataTableRowChangeEvent(SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public SummaryOfMonthlyInventoryPerBrandDataSetDataTableRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591